# reusable workflow triggered by other actions
name: CI

on:
  workflow_call:
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true

jobs:
  lib-check:
    name: Check libraries
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_quality-checks.yaml@main
    secrets: inherit
    with:
        charm-path: "."

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v5.3.0
      with:
        python-version: 3.8
    - run: pip install tox
    - run: tox -e lint

  terraform-checks:
    name: Terraform
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/terraform-checks.yaml@main
    with:
      charm-path: .

  unit-test:
    name: Unit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.8
      - run: pip install tox
      - run: tox -e unit

  integration-test:
    name: Integration
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.8

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
            provider: microk8s
            channel: 1.32-strict/stable
            charmcraft-channel: 3.x/stable
            juju-channel: 3.6/stable

      - run: KUBECONFIG=$HOME/.kube/config tox -e integration
