# reusable workflow triggered by other actions
name: Tests

on:
  workflow_call:
    secrets:
      charmcraft-credentials:
        required: true

jobs:

  lib-check:
    name: Check libraries
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.0.0-rc
        with:
          credentials: "${{ secrets.charmcraft-credentials }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: pip install tox
    - run: tox -e lint

  unit-test:
    name: Unit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: pip install tox
      - run: tox -e unit

  integration-test:
    name: Integration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
            provider: microk8s
            channel: 1.22/stable
            charmcraft-channel: latest/candidate
            # Pinned to 2.3.34 due to https://bugs.launchpad.net/juju/+bug/1992833
            # This should be fixed on release of juju 2.3.36 + libjuju 3.0.3
            bootstrap-options: --agent-version="2.9.34"

      - run: sg microk8s -c "KUBECONFIG=$HOME/.kube/config tox -e integration"
