# reusable workflow triggered by other actions
name: CI

on:
  workflow_call:
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true

jobs:
  lib-check:
    name: Check libraries
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_quality-checks.yaml@main
    secrets: inherit
    with:
        charm-path: "."

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: pip install tox
    - run: tox -e lint

  unit-test:
    name: Unit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: pip install tox
      - run: tox -e unit

  integration-test:
    name: Integration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
            provider: microk8s
            channel: 1.24/stable
            charmcraft-channel: latest/candidate
            juju-channel: 2.9/stable

      - run: sg microk8s -c "KUBECONFIG=$HOME/.kube/config tox -e integration"
